-- MySQL Script generated by MySQL Workbench
-- Tue Aug 30 15:04:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mao_Obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mao_Obra` (
  `id` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Especialidades` (
  `id` INT NOT NULL,
  `Dessricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico` (
  `idMecanicos` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Especialidades_id` INT NOT NULL,
  PRIMARY KEY (`idMecanicos`, `Especialidades_id`),
  INDEX `fk_Mecanico_Especialidades1_idx` (`Especialidades_id` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_Especialidades1`
    FOREIGN KEY (`Especialidades_id`)
    REFERENCES `mydb`.`Especialidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculos` (
  `id` INT NOT NULL,
  `Cliente_id` INT NOT NULL,
  `Placa` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NULL DEFAULT 'A',
  PRIMARY KEY (`id`, `Cliente_id`),
  INDEX `fk_Veiculos_Cliente_idx` (`Cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculos_Cliente`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `mydb`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pecas` (
  `id` INT NOT NULL,
  `Dessricao` VARCHAR(45) NOT NULL,
  `Valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipes` (
  `idEquipes` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEquipes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem` (
  `id` INT NOT NULL,
  `Veiculos_id` INT NOT NULL,
  `idEquipes` INT NOT NULL,
  `Tipo_Servico` VARCHAR(45) NOT NULL,
  `Data_Autorizacao` DATE NOT NULL,
  `Data_Emissao` DATE NOT NULL,
  `Data_Entrega` DATE NOT NULL,
  `Valor_Total` FLOAT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Data_Conclusao` DATE NOT NULL,
  PRIMARY KEY (`id`, `Veiculos_id`, `idEquipes`),
  INDEX `fk_Ordem_Veiculos1_idx` (`Veiculos_id` ASC) VISIBLE,
  INDEX `fk_Ordem_Equipes1_idx` (`idEquipes` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Veiculos1`
    FOREIGN KEY (`Veiculos_id`)
    REFERENCES `mydb`.`Veiculos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Equipes1`
    FOREIGN KEY (`idEquipes`)
    REFERENCES `mydb`.`Equipes` (`idEquipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem_Pecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem_Pecas` (
  `id` INT NOT NULL,
  `Ordem_id` INT NOT NULL,
  `Pecas_id` INT NOT NULL,
  `Valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`, `Ordem_id`, `Pecas_id`),
  INDEX `fk_Ordem_Pecas_Ordem1_idx` (`Ordem_id` ASC) VISIBLE,
  INDEX `fk_Ordem_Pecas_Pecas1_idx` (`Pecas_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Pecas_Ordem1`
    FOREIGN KEY (`Ordem_id`)
    REFERENCES `mydb`.`Ordem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Pecas_Pecas1`
    FOREIGN KEY (`Pecas_id`)
    REFERENCES `mydb`.`Pecas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem_Mao_Obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem_Mao_Obra` (
  `id` INT NOT NULL,
  `Servico_id` INT NOT NULL,
  `Ordem_id` INT NOT NULL,
  `Valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`, `Servico_id`, `Ordem_id`),
  INDEX `fk_Ordem_Servico_Servico1_idx` (`Servico_id` ASC) VISIBLE,
  INDEX `fk_Ordem_Mao_Obra_Ordem1_idx` (`Ordem_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Servico_Servico1`
    FOREIGN KEY (`Servico_id`)
    REFERENCES `mydb`.`Mao_Obra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Mao_Obra_Ordem1`
    FOREIGN KEY (`Ordem_id`)
    REFERENCES `mydb`.`Ordem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe_Mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe_Mecanicos` (
  `idEquipe_Mecanicos` INT NOT NULL,
  `Equipes_idEquipes` INT NOT NULL,
  `Mecanico_idMecanicos` INT NOT NULL,
  PRIMARY KEY (`idEquipe_Mecanicos`, `Equipes_idEquipes`, `Mecanico_idMecanicos`),
  INDEX `fk_Equipe_Mecanicos_Equipes1_idx` (`Equipes_idEquipes` ASC) VISIBLE,
  INDEX `fk_Equipe_Mecanicos_Mecanico1_idx` (`Mecanico_idMecanicos` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_Mecanicos_Equipes1`
    FOREIGN KEY (`Equipes_idEquipes`)
    REFERENCES `mydb`.`Equipes` (`idEquipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe_Mecanicos_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanicos`)
    REFERENCES `mydb`.`Mecanico` (`idMecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
